### ISSUE TITLE
自己改的数据，可以看下吗。

### ISSUE THREAD

**Issue by sunke5616** [minglich/logitech-pubg#11]
recoil_table["m416"] = {
    basic={49,37,38,41,45,48,49,49,59,53,54,53,57,58,60,62},
    basictimes = 1.05,
	
    full={49,38,38,42,46,49,50,50,51,52,53,52,58,59,60,63},
    fulltimes = 1.05*0.75*1*0.98,
	
    holdbreathtimes = 1.25,
自己就在这个数值上面调的，不知道对不对，裸配还凑合，但是满配怎么都还会压不住。
自己调数据是这样调吗？

**Comment by minglich** [comment]
script can't control random recoil ,the bigger recoil is ,the bigger random.
