### ISSUE TITLE
Stop when shooting continuously

### ISSUE THREAD

**Issue by Monodiess** [minglich/logitech-pubg#3]
It will stop when it shoots 10-20 bullets. The log is reported as follows.
![qq 20180506172955](https://user-images.githubusercontent.com/30265079/39671948-21495d1c-5154-11e8-9773-be75548cdaec.png)

**Comment by smsi80** [comment]
you can fix this?

**Comment by mcalis** [comment]
I get the same

**Comment by minglich** [comment]
Ok i know .
