### ISSUE TITLE
logitech g213 mod

### ISSUE THREAD

**Issue by tr00tr** [minglich/logitech-pubg#4]
[pubg g213(keybord add).zip](https://github.com/minglich/logitech-pubg/files/1977893/pubg.g213.keybord.add.zip)

I integrated it with the keyboard. F1 F2 F3 keys activate.
I want the key to flash when I press F1. How Can I do that?
![adsiz](https://user-images.githubusercontent.com/38983765/39676466-fc068f78-5173-11e8-9b8e-55dbcfa0f283.jpg)

**Comment by burnedredline** [comment]
Only g key bro ex g1 g2 g3 g4 g5 g6 g7 g8 g9 g10 g11 
Turkish:Sadece g harfiyle başlayan logitech ürünlerinin klavye ve farelerinde gkeylere atama yapabilirsin öyle kafana göre f1 f2 olmaz cihaz kabul etmiyor ctrl Lshift Rshift Lalt Ralt Numlock capslock tuşlarına atayabilirsin.
