### ISSUE TITLE
What should I change in my game, because it does not work for me any guns

### ISSUE THREAD

**Issue by smsi80** [minglich/logitech-pubg#5]
What should I change in my game, because it does not work for me any guns 
pless help me

**Comment by duwolf1983** [comment]
m2 same taking down so much or pulling up more i cant get it too whats going here

**Comment by jinny7899** [comment]
work awsome for me

**Comment by smsi80** [comment]
what your settings?

**Comment by xfighterxyz** [comment]
U need to change virtical recoil to 1 instead of .70

**Comment by smsi80** [comment]
my vertical recoil is 1 but not working

**Comment by smsi80** [comment]
can somebody give me the no recoil he use and that works great and what is your settings in-game?

**Comment by doctorwwho** [comment]
change it yourself to fit
