### ISSUE TITLE
Any logitech gaming mouse?

### ISSUE THREAD

**Issue by Aikawaconda** [minglich/logitech-pubg#6]
What kind of logitech gaming mouse do i have to use? I am going to buy logitech g mouse. But i dont know what mouse do i have to buy? Can i use the cheapest logitech g mouse G102 ? Does this mouse work with the no recoil script?

**Comment by thegringooo** [comment]
should work with every g mouse. the g502 is great!

**Comment by Aikawaconda** [comment]
I see. Is it ok to use the cheap logitech mouse to use the script ? The G102 only have few button n g502 have many buttons right

**Comment by thegringooo** [comment]
sure. but for every weapon you want to use you need a button, and one button to deactivate the profil

**Comment by Aikawaconda** [comment]
Alright.. Thank you for the explain how it works.
